languageCode = "en-us"
title = "wstrm"
enableRobotsTXT = true
enableEmoji = true
# Copyright notice. This is displayer in the footer.
copyright = "Copyright &copy; 2018-2020 William Wennerström"
theme = "hugo_theme_pickles"

[params]
custom_css = [
    "/css/custom.css"
]
paginate = 10
# Social accounts. Link to these accounts are displayed in the header and
# footer
#twitter = "Your Twitter username"
#facebook = "Your Facebook username"
#instagram = "Your Instagram username"
#googleplus = "Your Google+ account URL" # https://plus.google.com/u/0/xxxxxx
github = "wstrm"
gitlab = "wstrm"
#npm = "Your npm username"
#codepen = "Your CodePen username"
#dribbble = "Your Dribbble username"
#fivehundredpx = "Your 500px username" # 500px
#flickr = "Your Flickr username"
#pinterest = "Your Pinterest username"
#tumblr = "Your Tumblr username"
#vimeo = "Your Vimeo username"
#youtube = "Your YouTube username"
linkedin = "william-wennerstrom"
# Disqus shortname
#disqus = ""
# Google Analytics API key.
#ga_api_key = "Your Google Analytics tracking id"
author = "William Wennerström"
authorwebsite = "wstrm.dev"
avatar = "/images/avatar.png"
contact = "mailto:william@wstrm.dev"
bio = "Hello, I like computers."
# Short subtitle/tagline. This is displayed in the header.
subtitle = ""
# Logo image. This is displayed ogp image.
#logo = "/images/avatar.jpg"
#favicon = "/path/to/favicon"

[[menu.main]]
name = "Blog"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[related]
# Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
threshold = 80

# To get stable "See also" sections we, by default, exclude newer related pages.
includeNewer = false

# Will lower case keywords in both queries and in the indexes.
toLower = false

[[related.indices]]
name = "keywords"
weight = 150
[[related.indices]]
name  = "author"
toLower = true
weight = 30
[[related.indices]]
name  = "tags"
weight = 100
[[related.indices]]
name  = "date"
weight = 10
pattern = "2017"

[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^pandoc$']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']

  [security.funcs]
    getenv = ['^HUGO_']

  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']
